### ISSUE TITLE
Can't scan QR codes

### ISSUE THREAD

**Issue by turbamulta** [remcoros/sparrow-webtop-startos#11]
Cam permission is granted to the browser tab, "Webcam Exception" happens to any airgapped wallet. 

![image](https://github.com/remcoros/sparrow-webtop-startos/assets/103970332/5de49e23-6573-4585-834a-4288ae76e8c5)

**Comment by remcoros** [comment]
Webcams and USB devices are not supported, as that requires both browser support and tight StartOS integration, which is just not possible currently for services in StartOS. (it needs a kernel module in StartOS, I tried to hack it in, but couldn't get that to work either)

**Comment by turbamulta** [comment]
> Webcams and USB devices are not supported, as that requires both browser support and tight StartOS integration, which is just not possible currently for services in StartOS. (it needs a kernel module in StartOS, I tried to hack it in, but couldn't get that to work either)

The BTCPayServer service is able to scan QR codes from the webcam, but probably has a tighter integration in the OS that requires significant effort. I asked just in case it was something easy enough, thanks for trying.

**Comment by remcoros** [comment]
> > Webcams and USB devices are not supported, as that requires both browser support and tight StartOS integration, which is just not possible currently for services in StartOS. (it needs a kernel module in StartOS, I tried to hack it in, but couldn't get that to work either)
> 
> The BTCPayServer service is able to scan QR codes from the webcam, but probably has a tighter integration in the OS that requires significant effort. I asked just in case it was something easy enough, thanks for trying.

That's comparing apples to oranges.

BTCPayServer is a normal web application, using html and javascript directly in the browser, so can use all the available browser features as a normal web application does.

Sparrow is a desktop application, running on a linux desktop inside a docker container. It's not a web application running in your browser. It captures the desktop using ffmpeg and streams it to the browser using this technology: https://kasmweb.com/kasmvnc

KasmVNC supports passtrough of webcams using the webbrowser API, but it requires a lot more then a 'normal html/javascript app in the browser' needs.

See this: https://kasmweb.com/docs/latest/guide/webcam_passthrough.html

The instructions are for Kasm Workspaces, but the underlying tech is the same (KasmVNC).

You need:
- the v4l2loopback kernel module loaded in the host OS
- Pass-trough "/dev/video0" to the docker container

The first can be hacked in StartOS (if not using uefi secure boot)
The second is currently just not possible, as services in StartOS cannot choose the devices mapped to the container.

On top of that, I think it needs to be a 'privileged' container, which for obvious reasons, StartOS does not allow.
